LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE_TAGS := optional

LOCAL_SRC_FILES := \
	Exynos_OMX_Component_Register.c \
	Exynos_OMX_Core.c

LOCAL_PRELINK_MODULE := false
LOCAL_MODULE := libExynosOMX_Core
LOCAL_PROPRIETARY_MODULE := true

LOCAL_CFLAGS :=

LOCAL_ARM_MODE := arm

LOCAL_STATIC_LIBRARIES := libExynosOMX_OSAL libExynosOMX_Basecomponent
LOCAL_SHARED_LIBRARIES := libc libdl libcutils libutils liblog \
	libExynosOMX_Resourcemanager

LOCAL_C_INCLUDES := \
	$(EXYNOS_OMX_INC)/exynos \
	$(EXYNOS_OMX_TOP)/osal \
	$(EXYNOS_OMX_TOP)/component/common

ifeq ($(BOARD_USE_KHRONOS_OMX_HEADER), true)
LOCAL_CFLAGS += -DUSE_KHRONOS_OMX_HEADER
LOCAL_C_INCLUDES += $(EXYNOS_OMX_INC)/khronos
else
ifeq ($(BOARD_USE_ANDROID), true)
LOCAL_HEADER_LIBRARIES := media_plugin_headers
LOCAL_CFLAGS += -DUSE_ANDROID
endif
endif

ifeq ($(BOARD_DISABLE_RAPID_COMPONENT_LOAD), true)
LOCAL_CFLAGS += -DUSE_DISABLE_RAPID_COMPONENT_LOAD
endif

ifeq ($(BOARD_USE_CUSTOM_COMPONENT_SUPPORT), true)
LOCAL_CFLAGS += -DUSE_CUSTOM_COMPONENT_SUPPORT
endif

ifeq ($(BOARD_USE_ALP_AUDIO), true)
    ifeq ($(BOARD_USE_SEIREN_AUDIO), true)
    LOCAL_CFLAGS += -DUSE_SEIREN_AUDIO_COMPONENT_LOAD
    else
    LOCAL_CFLAGS += -DUSE_ALP_AUDIO_COMPONENT_LOAD
    endif
endif

ifeq ($(EXYNOS_OMX_SUPPORT_TUNNELING), true)
LOCAL_CFLAGS += -DTUNNELING_SUPPORT
endif

ifeq ($(EXYNOS_OMX_SUPPORT_EGL_IMAGE), true)
LOCAL_CFLAGS += -DEGL_IMAGE_SUPPORT
endif

ifdef BOARD_EXYNOS_S10B_FORMAT_ALIGN
LOCAL_CFLAGS += -DS10B_FORMAT_8B_ALIGNMENT=$(BOARD_EXYNOS_S10B_FORMAT_ALIGN)
endif

ifneq ($(BOARD_USE_HEVCENC_SUPPORT), true)
LOCAL_CFLAGS += -DDISABLE_HEVC_ENC_CODEC
LOCAL_CFLAGS += -DDISABLE_CODEC_COMP
endif

ifneq ($(BOARD_USE_VP9DEC_SUPPORT), true)
LOCAL_CFLAGS += -DDISABLE_VP9_DEC_CODEC
LOCAL_CFLAGS += -DDISABLE_CODEC_COMP
endif

ifneq ($(BOARD_USE_VP9ENC_SUPPORT), true)
LOCAL_CFLAGS += -DDISABLE_VP9_ENC_CODEC
LOCAL_CFLAGS += -DDISABLE_CODEC_COMP
endif

ifneq ($(BOARD_USE_WFDENC_SUPPORT), true)
LOCAL_CFLAGS += -DDISABLE_WFD_ENC_CODEC
LOCAL_CFLAGS += -DDISABLE_CODEC_COMP
endif

ifeq ($(BOARD_USE_NON_DRM_CODEC_ONLY), true)
LOCAL_CFLAGS += -DDISABLE_SECURE_CODEC
LOCAL_CFLAGS += -DDISABLE_CODEC_COMP
endif

LOCAL_CFLAGS += -Wno-unused-variable -Wno-unused-label

include $(BUILD_SHARED_LIBRARY)
